# CMake generated Testfile for 
# Source directory: /home1/rahul/Work/moose-core
# Build directory: /home1/rahul/Work/moose-core/_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(moose.bin-raw-run "/home1/rahul/Work/moose-core/_build/moose.bin" "-u" "-q")
SET_TESTS_PROPERTIES(moose.bin-raw-run PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/_build")
ADD_TEST(pymoose-test-synchan "/usr/bin/python" "test_synchan.py")
SET_TESTS_PROPERTIES(pymoose-test-synchan PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/tests/python")
ADD_TEST(pymoose-test-function "/usr/bin/python" "test_function.py")
SET_TESTS_PROPERTIES(pymoose-test-function PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/tests/python")
ADD_TEST(pymoose-test-vec "/usr/bin/python" "test_vec.py")
SET_TESTS_PROPERTIES(pymoose-test-vec PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/tests/python")
ADD_TEST(pymoose-pyrun "/usr/bin/python" "test_pyrun.py")
SET_TESTS_PROPERTIES(pymoose-pyrun PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/tests/python")
ADD_TEST(pymoose-neuroml-reader-test "/usr/bin/python" "test_neuroml.py")
SET_TESTS_PROPERTIES(pymoose-neuroml-reader-test PROPERTIES  WORKING_DIRECTORY "/home1/rahul/Work/moose-core/tests/python")
SUBDIRS(basecode)
SUBDIRS(msg)
SUBDIRS(shell)
SUBDIRS(randnum)
SUBDIRS(scheduling)
SUBDIRS(biophysics)
SUBDIRS(builtins)
SUBDIRS(utility)
SUBDIRS(external/muparser)
SUBDIRS(external/tinyxml)
SUBDIRS(mesh)
SUBDIRS(sbml)
SUBDIRS(mpi)
SUBDIRS(signeur)
SUBDIRS(ksolve)
SUBDIRS(hsolve)
SUBDIRS(diffusion)
SUBDIRS(device)
SUBDIRS(benchmarks)
SUBDIRS(kinetics)
SUBDIRS(synapse)
SUBDIRS(intfire)
SUBDIRS(examples)
SUBDIRS(pymoose)
